### ISSUE TITLE
Crashes on certain file types like a .MSI or .JSON

### ISSUE THREAD

**Issue by dekenless** [GetoXs/MimeDetect#1]
Crashes on certain file types like a .MSI or .JSON:

System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=mscorlib
  StackTrace:
   at System.String.wcslen(Char* ptr)
   at System.String.CtorCharPtr(Char* ptr)
   at System.Runtime.InteropServices.Marshal.PtrToStringUni(IntPtr ptr)
   at Winista.MimeDetect.URLMONMimeDetect.urlmonMimeDetect.GetMimeFromFile(String filename)
   at Winista.Mime.MimeTypes.GetMimeTypeFromFile(String filePath)

**Comment by wendt88** [comment]
Seems more a problem of interop in ASP.NET

issue could found here:
https://stackoverflow.com/a/26061243

with a fix here:
https://stackoverflow.com/a/18554243
